### ISSUE TITLE
Possible discord bot token leak

### ISSUE THREAD

**Issue by IeuanK** [robot-rover/SovietBot#1]
Hi there,

Through a very basic github search I found your project. In this project you have your Discord bot token publicly available.

I am hereby simply notifying you of this fact, since many people are unaware of sensitive data being in their repositories.

If this token is your actual token you should [regenerate it](https://discordapp.com/developers/applications/me) at the earliest convenience. To prevent this in the future you may want to read [the offical guide on sensitive data](https://help.github.com/articles/remove-sensitive-data/).

In case you are already aware of this and have taken steps to fix it feel free to regard this issue as non-existent.

Kind regards.

**Comment by robot-rover** [comment]
I want to thank you for this heads up. I had the configuration file present in the .gitignore file but it appears that this has not worked...
I will regenerate the token. While I was aware this should not be publicly available, I put the file in the gitignore and simply forgot about it.
Thanks!
EDIT: I also want to add that this was the test token, which only has access to my test server, so while it is not a big security risk, I still don't want it floating around on the internet.
